---
- name: Add an apt key to install kubernetis
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add apt source
  template: src=docker.list.j2 dest=/etc/apt/sources.list.d/docker.list

- name: Update repositories cache and Install "Docker CE (Community Edition)" package
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Add pi to group docker
  user:
    name: pi
    groups: docker
    append: yes
